export component Test {
    property <int> count: 0;

    Rectangle {
        border-radius: 20px;
        width: 200px;
        height: 200px;
        background: #f5c84e;

        drop-shadow-color: gray;

        drop-shadow-offset-x: 2px;
        drop-shadow-offset-y: 2px;
        drop-shadow-blur: 3px;
    

        Text {
            text: count;
            font-size: 40px;
            font-family: "Verdana";
        }

        TouchArea {
            clicked => {
                count += 1;
            }
        }
    }
}

export component MyApp {

    min-width: 100px;
    max-width: 1000px;

    min-height: 100px;
    max-height: 1000px;

    // width: 500px;
    // height: 500px;

    VerticalLayout {
        HorizontalLayout {
            Test { }

            Test { }
        }

        HorizontalLayout {
            Test { }

            Test { }
        }
    }
}
